site_name: 张雪峰语录
site_url: https://zhangxuefeng.zhihu.blog/
site_author: shutouyabo
site_description: >-
  wiki bin

repo_name: 张雪峰语录
repo_url: https://github.com/shutouyabo/zhangxuefeng.github.io/

copyright: Copyright &copy; 2021-present <a href="https://github.com/shutouyabo" target="_blank" rel="noopener noreferrer">shutouyabo</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true

  - search:
      lang:
        - zh
  - git-revision-date:
  - minify:
      minify_html: true
  - open-in-new-tab:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shutouyabo/zhangxuefeng.github.io/
  analytics:
    provider: google
    property: G-KJB4RXSKZG

nav:
  - 前言: "index.md"
  - 张雪峰系统:
      - "张雪峰 - 著作与系统思考": "张雪峰系统/张雪峰 - 著作与系统思考.md"
      - "张雪峰 - 长对话与即兴思考": "张雪峰系统/张雪峰 - 长对话与即兴思考.md"
      - "张雪峰 - 碎片表达与风格DNA": "张雪峰系统/张雪峰 - 碎片表达与风格DNA.md"
      - "张雪峰 - 他者视角与批评": "张雪峰系统/张雪峰 - 他者视角与批评.md"
      - "张雪峰 - 决策记录与行动": "张雪峰系统/张雪峰 - 决策记录与行动.md"
      - "张雪峰 - 人物时间线": "张雪峰系统/张雪峰 - 人物时间线.md"
  - 张雪峰视角对话实录:
      - "张雪峰视角对话实录 1": "张雪峰视角对话实录/张雪峰视角对话实录 1.md"
  - 张雪峰谈考研 1:
      - "“人间清醒”张雪峰：为啥网友都在力挺,他却“跪下”了，唐尚珺就是例子。": "张雪峰谈考研 1/“人间清醒”张雪峰：为啥网友都在力挺,他却“跪下”了，唐尚珺就是例子。.md"
      - "“三不问，四不说”，聪明人一生都在这么做，你还在糊涂吗？": "张雪峰谈考研 1/“三不问，四不说”，聪明人一生都在这么做，你还在糊涂吗？.md"
      - "“张雪峰效应”展现威力：但追高杀跌式的志愿填报真的科学吗？": "张雪峰谈考研 1/“张雪峰效应”展现威力：但追高杀跌式的志愿填报真的科学吗？.md"
      - "670发分的状元，滑档了，可见张雪峰的影响力有多大。": "张雪峰谈考研 1/670发分的状元，滑档了，可见张雪峰的影响力有多大。.md"
      - "复读15年的唐尚珺一场直播挣了78万。": "张雪峰谈考研 1/复读15年的唐尚珺一场直播挣了78万。.md"
      - "好友透露唐尚珺放弃补录：做了激烈思想斗争，对未来还很迷茫。": "张雪峰谈考研 1/好友透露唐尚珺放弃补录：做了激烈思想斗争，对未来还很迷茫。.md"
      - "今年滑档的人太多了，张雪峰可能要完了。": "张雪峰谈考研 1/今年滑档的人太多了，张雪峰可能要完了。.md"
      - "唐尚郡，知识改变命运，可能一直从小时候都在欺骗我们，放弃了。": "张雪峰谈考研 1/唐尚郡，知识改变命运，可能一直从小时候都在欺骗我们，放弃了。.md"
      - "唐尚珺 被退档一系列事情，到底是想上大学？复读还是当网红": "张雪峰谈考研 1/唐尚珺 被退档一系列事情，到底是想上大学？复读还是当网红.md"
      - "唐尚珺，知识改变命运，其实一直在欺骗我们，那有知识改变命运。": "张雪峰谈考研 1/唐尚珺，知识改变命运，其实一直在欺骗我们，那有知识改变命运。.md"
      - "唐尚珺被退档，大家才知道我的重要性，非要把路走绝才知道吗？": "张雪峰谈考研 1/唐尚珺被退档，大家才知道我的重要性，非要把路走绝才知道吗？.md"
      - "一家长质疑国科大的教学，让张雪峰老师给怼的！内出血。": "张雪峰谈考研 1/一家长质疑国科大的教学，让张雪峰老师给怼的！内出血。.md"
  - 张雪峰谈考研 2:
      - "有出国留学想法的话就不要报医学专业了，不要问为什么，肾都没了，还学什么医。": "张雪峰谈考研 2/有出国留学想法的话就不要报医学专业了，不要问为什么，肾都没了，还学什么医。.md"
      - "“摆烂只能越来越烂，积极向上是最基本的，剩下的只能交给命运。": "张雪峰谈考研 2/“摆烂只能越来越烂，积极向上是最基本的，剩下的只能交给命运。.md"
      - "60岁的老大爷都不厉害，我身体已经被老婆掏空了。": "张雪峰谈考研 2/60岁的老大爷都不厉害，我身体已经被老婆掏空了。.md"
      - "211研究生火锅店打工，送他两个字，活该。": "张雪峰谈考研 2/211研究生火锅店打工，送他两个字，活该。.md"
      - "985硕士毕业，一个月3000，现在的就业环境有多差！": "张雪峰谈考研 2/985硕士毕业，一个月3000，现在的就业环境有多差！.md"
      - "985硕士毕业，一个月工资3000元，唐尚珺你复读个寂寞呀。": "张雪峰谈考研 2/985硕士毕业，一个月工资3000元，唐尚珺你复读个寂寞呀。.md"
      - "985一定比二本好吗，我看不一定。": "张雪峰谈考研 2/985一定比二本好吗，我看不一定。.md"
      - "2023年大部分人失业，很多年轻人回家躺平，这就是专业不选好的代价。": "张雪峰谈考研 2/2023年大部分人失业，很多年轻人回家躺平，这就是专业不选好的代价。.md"
      - "chatgtp都把互联网搞垮了，现在大部分失业，你还报计算机。": "张雪峰谈考研 2/chatgtp都把互联网搞垮了，现在大部分失业，你还报计算机。.md"
      - "不同地区，不同的口腔诊所，口腔门诊部，口腔医院，学历是有很大的差别": "张雪峰谈考研 2/不同地区，不同的口腔诊所，口腔门诊部，口腔医院，学历是有很大的差别.md"
      - "不要歧视任何职业，每个行业只有做到极致，钱跟本花不完。": "张雪峰谈考研 2/不要歧视任何职业，每个行业只有做到极致，钱跟本花不完。.md"
      - "不要歧视任何职业，每个行业只有做到极致，钱跟本花不完。": "张雪峰谈考研 2/不要歧视任何职业，每个行业只有做到极致，钱跟本花不完。.md"
      - "不要为了面子去上名校，孩子毕业会找不到工作的。": "张雪峰谈考研 2/不要为了面子去上名校，孩子毕业会找不到工作的。.md"
      - "不要在当老师了，国家在制裁这个行业，而且巨卷。": "张雪峰谈考研 2/不要在当老师了，国家在制裁这个行业，而且巨卷。.md"
      - "出国读研，还不如读宁诺和西埔，远远吊打外国研究生。": "张雪峰谈考研 2/出国读研，还不如读宁诺和西埔，远远吊打外国研究生。.md"
      - "出生率都负增长了，还报什么师范，到时候死路一条。": "张雪峰谈考研 2/出生率都负增长了，还报什么师范，到时候死路一条。.md"
      - "但凡唐尚珺看过我一个视频，也不会被退档，活该，活该，活该！": "张雪峰谈考研 2/但凡唐尚珺看过我一个视频，也不会被退档，活该，活该，活该！.md"
      - "低分没有好的公办院校和专业，选民办不要想着怕浪费分，选地域，考研率和选什么样的专业，想老公选汉语言文学，法学，会计。": "张雪峰谈考研 2/低分没有好的公办院校和专业，选民办不要想着怕浪费分，选地域，考研率和选什么样的专业，想老公选汉语言文学，法学，会计。.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
      - "": "张雪峰谈考研 2/.md"
